### ISSUE TITLE
[SUBMISSION] Meow Attack

### ISSUE THREAD

**Issue by ImLoadingUuU** [ScriptWare-Software/swm-themes#5]
# Requirements
- [X] To mark a requirement as completed, put an X in the box, like this line.
- [X] This is a theme that **I** have created, not someone else.
- [X] This is a theme for Script-Ware M (not the dashboard or Script-Ware for Windows)
- [x] All assets (such as images), if any, are hosted on trusted sources (such as Imgur or Discord)

# Tag your theme
- [ ] Background image
- [ ] Animated
- [x] Custom (you wrote your own custom CSS)
- [X] Overhaul (makes major changes to the SWM UI, for example, the "Red Sea" theme)

# Write a short description of your theme
Cat Destroyed Script-Ware M , BUT Cat is cute so its Okay!!
<img width="1198" alt="截圖 2022-06-16 下午4 51 44" src="https://user-images.githubusercontent.com/69704016/174032325-a3f95166-56e5-4c30-9298-4dee12d0dc5d.png">
# Upload your theme.

Drag your theme file into this text box, if you get an error about it being unsupported, rename it to .txt on the end.

[meow.txt](https://github.com/ScriptWare-Software/swm-themes/files/8917276/meow.txt)

**Comment by theLMGN** [comment]
Apologies, however we are not able to accept themes as this may cause users to be confused when operating Script-Ware M. You are free to redistribute the theme through other means such as the Discord channel, however we are not able to add it here.
